// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Vesc_Dashboard

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Loading
void ui_Loading_screen_init(void);
lv_obj_t *ui_Loading;
lv_obj_t *ui_Image1;
lv_obj_t *ui_SpeedText;
lv_obj_t *ui_SpeedValue;
lv_obj_t *ui_CurrentMeterText;
lv_obj_t *ui_CurrentMeterValue;
lv_obj_t *ui_VoltMeterText;
lv_obj_t *ui_VoltMeterValue;
lv_obj_t *ui____initial_actions0;
const lv_image_dsc_t *ui_imgset_super[1] = {&ui_img_super73_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Loading_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Loading);
}
