// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Vesc_Dashboard

#ifndef _VESC_DASHBOARD_UI_H
#define _VESC_DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Loading
void ui_Loading_screen_init(void);
extern lv_obj_t *ui_Loading;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_SpeedText;
extern lv_obj_t *ui_SpeedValue;
extern lv_obj_t *ui_CurrentMeterText;
extern lv_obj_t *ui_CurrentMeterValue;
extern lv_obj_t *ui_VoltMeterText;
extern lv_obj_t *ui_VoltMeterValue;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_super73_png);   // assets/Super73.png


LV_FONT_DECLARE( ui_font_Super73font15);
LV_FONT_DECLARE( ui_font_Super73font25);
LV_FONT_DECLARE( ui_font_Super73font30);
LV_FONT_DECLARE( ui_font_Super73font40);
LV_FONT_DECLARE( ui_font_Super73font50);
LV_FONT_DECLARE( ui_font_Super73font80);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
